# Generated by Django 5.2.6 on 2025-09-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('feeling', models.CharField(choices=[('Good', 'Good'), ('Normal', 'Normal'), ('Ok', 'Ok'), ('Bad', 'Bad')])),
            ],
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journalentry')),
            ],
        ),
    ]
